Vagrant.configure("2") do |config|

    # Master Nodes
    MasterCount = 1
    (1..MasterCount).each do |i|
        config.vm.define "k8s-master-#{i}" do |master|
            master.vm.box = "generic/ubuntu2004"
            master.vm.box_version = "3.6.8"
            master.vm.hostname = "k8s-master-#{i}"
            master.vm.network "private_network", ip: "172.16.1.1#{i}"

            master.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-master-#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end
        end
    end

    # Worker Nodes
    WorkerCount = 1
    (1..WorkerCount).each do |i|
        config.vm.define "k8s-worker-#{i}" do |worker|
            worker.vm.box = "generic/ubuntu2004"
            worker.vm.box_version = "3.6.8"
            worker.vm.hostname = "k8s-worker-#{i}"
            worker.vm.network "private_network", ip: "172.16.2.1#{i}"

            worker.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-worker-#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end
        end
    end

    # etcd Nodes
    EtcdCount = 3
    (1..EtcdCount).each do |i|
        config.vm.define "k8s-etcd-#{i}" do |etcd|
            etcd.vm.box = "generic/ubuntu2004"
            etcd.vm.box_version = "3.6.8"
            etcd.vm.hostname = "k8s-etcd-#{i}"
            etcd.vm.network "private_network", ip: "172.16.3.1#{i}"

            etcd.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-etcd-#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end
        end
    end

    config.vm.provision "file", source: "#{Dir.home}/.ssh/id_rsa_ci", destination: "/tmp/id_rsa"
    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa_ci.pub").first.strip
        s.inline = <<-SHELL
            # Create ci user
            useradd -s /bin/bash -d /home/ci/ -m -G sudo ci
            echo 'ci ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
            mkdir -p /home/ci/.ssh
            echo #{ssh_pub_key} >> /home/ci/.ssh/authorized_keys
            mv /tmp/id_rsa /home/ci/.ssh/id_rsa
            chown -R ci:ci /home/ci/.ssh
        SHELL
    end

end
